In [11]:
# !pip install transformers
# !pip install kobert-transformers
# !pip install mxnet-cu101
# !pip install gluonnlp pandas tqdm
!pip install sentencepiece==
# !pip install transformers==2.1.1
# !pip install torch==1.3.1
# !pip install -Iv botocore==1.17
# !pip install git+https://git@github.com/SKTBrain/KoBERT.git@master
# !pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from kobert_transformers import get_tokenizer, get_kobert_model
from sklearn.model_selection import train_test_split
from tqdm import tqdm, tqdm_notebook
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset

import warnings
import torch
import transformers
import pandas as pd
import numpy as np

device = torch.device("cuda:0")
warnings.filterwarnings(action='ignore')

In [13]:
from kobert_transformers import get_tokenizer
tokenizer = get_tokenizer()
# a = tokenizer.tokenize("[CLS] 한국어 모델을 공유합니다. [SEP]")
# max_length = 20
tensorized_input = tokenizer(
                            "한국어 모델을 공유합니다.",
                            max_length = 15,  # True or 'longest': Pad to the longest sequence in the batch
                            truncation=True,
                            return_tensors='pt',
                            add_special_tokens=True
                            )
# tokenizer.convert_tokens_to_ids(a)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'KoBertTokenizer'.


AttributeError: ignored

In [ ]:
tensorized_input['input_ids']

tensor([[   2, 4958, 6855, 2046, 7088, 1050, 7843,   54,    3]])

In [12]:
from transformers import BertTokenizer, AdamW
from transformers import get_linear_schedule_with_warmup
from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm, tqdm_notebook
from torch import nn
from torch.nn import functional as F
from sklearn.model_selection import train_test_split

import numpy as np
import torch
import random
import warnings
import gluonnlp as nlp



ModuleNotFoundError: ignored

In [ ]:
# bertmodel, vocab = get_pytorch_kobert_model()
# tokenizer = get_tokenizer()
# tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)
tokenizer = get_tokenizer()
model = get_kobert_model()

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'KoBertTokenizer'.


Downloading:   0%|          | 0.00/352M [00:00<?, ?B/s]

In [ ]:
# data = pd.read_csv("https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData.csv")
data = pd.read_csv("/content/drive/MyDrive/project/Classification/total_train_data.csv")

In [ ]:
# features = data['Q'].tolist()
# labels = data['label'].tolist()
queries = data['query'].tolist()
intents = data['intent'].tolist()

In [ ]:
train_data, valid_data, train_label, valid_label = train_test_split(queries, intents, test_size=0.2, shuffle=True, random_state=34)

In [ ]:
# config.py
MAX_LEN = 15
TRAIN_BATCH_SIZE =16
VALID_BATCH_SIZE =16
EPOCHS = 3
LR = 1e-5
WEIGHT_DECAY = 1e-2
BETA1 = 0.9
BETA2 = 0.999
MODEL_PATH = "/content/drive/MyDrive/Colab Notebooks/intent_class.pt"

In [ ]:
for i in train_data:
  print(tokenizer.tokenize(i))
  break

['▁날', '달', '걀', '▁예약', '▁취소', '어', '떻', '게', '▁해야', '▁돼']


In [ ]:
# dataset.py
class BERTDataset:
  def __init__(self, text, target, bert_tokenizer, max_len, pad, pair):
    self.text = text
    self.target = target
    self.tokenizer = bert_tokenizer
    self.max_len = max_len
    self.transform = [tokenizer(
                            i,
                            # padding="longest",  # True or 'longest': Pad to the longest sequence in the batch
                            max_seq_length = self.max_len,
                            truncation=True,
                            return_tensors='pt',
                            add_special_tokens=True
                            ) for i in self.text]
    # self.transform = [tokenizer.tokenize(i) for i in self.text]
    # self.transform = nlp.data.BERTSentenceTransform(self.tokenizer, max_seq_length=self.max_len, pad=pad, pair=pair)
    # self.sentences = [self.transform([i]) for i in text]
    self.labels = [np.int32(i) for i in target]

  def __len__(self):
    return (len(self.labels))
  
  def __getitem__(self, i):
    return self.transform[i], self.labels[i]

In [ ]:
train_dataset = BERTDataset(text=train_data,target=train_label, bert_tokenizer=tokenizer, max_len=MAX_LEN, pad=True, pair=False)
train_data_loader = DataLoader(train_dataset, batch_size = TRAIN_BATCH_SIZE, num_workers = 2, shuffle=True)

valid_dataset = BERTDataset(text=valid_data,target=valid_label, bert_tokenizer=tokenizer, max_len=MAX_LEN, pad=True, pair=False)
valid_data_loader = DataLoader(valid_dataset, batch_size = VALID_BATCH_SIZE, num_workers = 2, shuffle=True)

Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_length': 15} not recognized.
Keyword arguments {'max_seq_len

KeyboardInterrupt: ignored

In [ ]:
train_dataset.__getitem__(1)

({'input_ids': tensor([[   2, 2695, 7005, 7654, 5586, 3411, 7476, 6607, 7788, 6751, 7086, 5850,
            55,    3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])},
 3)

In [ ]:
class BERTClassifier(nn.Module):
    def __init__(self, bert, hidden_size = 768, num_classes=5, dr_rate=None, params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

In [ ]:
model = BERTClassifier(bertmodel, dr_rate=0.2).to(device)

In [ ]:
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]
optimizer = AdamW(optimizer_grouped_parameters, lr=LR)
loss_fn = nn.CrossEntropyLoss()
t_total = len(train_data_loader) * EPOCHS
warmup_step = int(t_total * 0.1)
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc
max_grad_norm = 1
log_interval = 200

In [ ]:
best_acc = 0
for e in range(EPOCHS):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_data_loader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(valid_data_loader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
        
    if test_acc > best_acc:
      best_acc = test_acc
      torch.save({'epoch':e,
                'state_dict':model.state_dict(),
                'optimizer': optimizer.state_dict(),
        }, MODEL_PATH)
    print("epoch {} validation acc {}".format(e+1, test_acc / (batch_id+1)))

  0%|          | 0/5283 [00:00<?, ?it/s]

epoch 1 batch id 1 loss 1.5000624656677246 train acc 0.5625
epoch 1 batch id 201 loss 1.4167041778564453 train acc 0.37468905472636815
epoch 1 batch id 401 loss 1.2298202514648438 train acc 0.39962593516209477
epoch 1 batch id 601 loss 1.3668646812438965 train acc 0.4281405990016639
epoch 1 batch id 801 loss 0.993280291557312 train acc 0.4463171036204744
epoch 1 batch id 1001 loss 0.8385078310966492 train acc 0.4589785214785215
epoch 1 batch id 1201 loss 0.8649979829788208 train acc 0.46497710241465445
epoch 1 batch id 1401 loss 1.0759810209274292 train acc 0.4693968593861527
epoch 1 batch id 1601 loss 0.927998423576355 train acc 0.4723610243597751
epoch 1 batch id 1801 loss 1.2588958740234375 train acc 0.47397279289283734
epoch 1 batch id 2001 loss 1.146135687828064 train acc 0.47598075962018993
epoch 1 batch id 2201 loss 1.0053616762161255 train acc 0.4770842798727851
epoch 1 batch id 2401 loss 0.9856611490249634 train acc 0.47935755935027075
epoch 1 batch id 2601 loss 1.195487260818

  0%|          | 0/1321 [00:00<?, ?it/s]

epoch 1 validation acc 0.5042108251324754


  0%|          | 0/5283 [00:00<?, ?it/s]

epoch 2 batch id 1 loss 0.980160117149353 train acc 0.5625
epoch 2 batch id 201 loss 0.8717403411865234 train acc 0.480410447761194
epoch 2 batch id 401 loss 1.2446914911270142 train acc 0.4985972568578554
epoch 2 batch id 601 loss 1.089397668838501 train acc 0.5004159733777038
epoch 2 batch id 801 loss 1.2058314085006714 train acc 0.4958645443196005
epoch 2 batch id 1001 loss 0.9423713684082031 train acc 0.4975024975024975
epoch 2 batch id 1201 loss 1.1267067193984985 train acc 0.49692964196502915
epoch 2 batch id 1401 loss 1.1129156351089478 train acc 0.4942897930049964
epoch 2 batch id 1601 loss 1.0749255418777466 train acc 0.49332448469706436
epoch 2 batch id 1801 loss 1.1002131700515747 train acc 0.49396168795113826
epoch 2 batch id 2001 loss 1.1904842853546143 train acc 0.495595952023988
epoch 2 batch id 2201 loss 0.9884526133537292 train acc 0.4964504770558837
epoch 2 batch id 2401 loss 0.6872953176498413 train acc 0.49661599333610995
epoch 2 batch id 2601 loss 0.864013850688934

  0%|          | 0/1321 [00:00<?, ?it/s]

epoch 2 validation acc 0.5042108251324754


  0%|          | 0/5283 [00:00<?, ?it/s]

epoch 3 batch id 1 loss 0.7821604013442993 train acc 0.6875
epoch 3 batch id 201 loss 1.021781325340271 train acc 0.5027985074626866
epoch 3 batch id 401 loss 0.8997359871864319 train acc 0.5059226932668329
epoch 3 batch id 601 loss 0.9435427188873291 train acc 0.507071547420965
epoch 3 batch id 801 loss 1.0071347951889038 train acc 0.5103776529338327
epoch 3 batch id 1001 loss 1.409563660621643 train acc 0.507554945054945
epoch 3 batch id 1201 loss 1.4671404361724854 train acc 0.5040591174021649
epoch 3 batch id 1401 loss 1.174933910369873 train acc 0.5024089935760171
epoch 3 batch id 1601 loss 1.0103113651275635 train acc 0.5004294191130544
epoch 3 batch id 1801 loss 1.1342214345932007 train acc 0.5011451971127152
epoch 3 batch id 2001 loss 0.8784767389297485 train acc 0.5006871564217891
epoch 3 batch id 2201 loss 1.106982946395874 train acc 0.4999148114493412
epoch 3 batch id 2401 loss 0.9698134660720825 train acc 0.5010412328196585
epoch 3 batch id 2601 loss 1.1587592363357544 trai

  0%|          | 0/1321 [00:00<?, ?it/s]

epoch 3 validation acc 0.5042423668937673


In [ ]:
import os, sys 
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
query = "오늘 탕수육 주문 가능한가요?"
transform = nlp.data.BERTSentenceTransform(tok, max_seq_length=15, pad=True, pair=False)
query_transform = transform(query)
query_data_loader = DataLoader(query_transform, batch_size=1)

In [ ]:
model_test = BERTClassifier(bertmodel)
model_test.load_state_dict(torch.load(MODEL_PATH)['state_dict'])
model_test.eval()


In [ ]:
for i in query_data_loader:
  print(i)

tensor([[   2, 3417,    3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
            1,    1,    1]], dtype=torch.int32)
tensor([3], dtype=torch.int32)
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=torch.int32)


In [ ]:
# token_ids = token_ids.long().to(device)
# segment_ids = segment_ids.long().to(device)
# valid_length= valid_length
out = model(torch.tensor(query_transform[0]), query_transform[1], query_transform[2])

TypeError: ignored

In [ ]:
pred_prob = []
with torch.no_grad():
    for batch in (query_transform):
        x = torch.tensor(batch[0], dtype = torch.float32, device = device)
        with torch.cuda.amp.autocast():
            pred = model_test(x)
            pred_prob.extend(pred.detach().cpu().numpy())
    pred_ensemble.append(pred_prob)